In [18]:
import pandas as pd

In [19]:
source_path_csv = '/Users/sundeepseethala/Documents/Sundeep Windows/sundeep windows/Job Applications/LinkedIn Learing/Ex_Files_ETL_Python_SQL/Exercise Files/Chapter_2/sample_data_csv.csv'
source_path_excel = '/Users/sundeepseethala/Documents/Sundeep Windows/sundeep windows/Job Applications/LinkedIn Learing/Ex_Files_ETL_Python_SQL/Exercise Files/Chapter_2/sample_data_excel.xlsx'
source_path_orders = '/Users/sundeepseethala/Documents/Sundeep Windows/sundeep windows/Job Applications/LinkedIn Learing/Ex_Files_ETL_Python_SQL/Exercise Files/Chapter_2/H+ Sport Orders.xlsx'
source_path_employees = '/Users/sundeepseethala/Documents/Sundeep Windows/sundeep windows/Job Applications/LinkedIn Learing/Ex_Files_ETL_Python_SQL/Exercise Files/Chapter_2/H+ Sport Employees.xlsx'
source_path_customers = '/Users/sundeepseethala/Documents/Sundeep Windows/sundeep windows/Job Applications/LinkedIn Learing/Ex_Files_ETL_Python_SQL/Exercise Files/Chapter_2/H+ Sport Customers.xlsx'
sample_csv_data = pd.read_csv(source_path_csv, header = None)
#sample_csv_data.head()

In [20]:
sample_data_excel = pd.read_excel(source_path_excel)
#sample_data_excel.head()

In [21]:
#This is part is Extraction of orders data from excel file.
sample_orders_data = pd.read_excel(source_path_orders)
#sample_orders_data.head()

In [22]:
#This is part is used for Transformation of Orders data as per business need.
#for this we are loading customers data.
sample_customers_data = pd.read_excel(source_path_customers, sheet_name='data')
sample_customers_data.head()

,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,Zipcode
0,100,Carol,Shaw,cshaw0@mlb.com,(206)804-8771,8157 Longview Court,Seattle,WA,98121
1,101,Elizabeth,Carr,ecarr1@oracle.com,(512)187-2507,3934 Petterle Trail,Austin,TX,78732
2,102,Ernest,Ramos,eramos2@plala.or.jp,(816)540-4257,8699 Clarendon Terrace,Kansas City,MO,64199
3,103,Jane,Carter,jcarter3@harvard.edu,(214)839-0542,2830 Novick Lane,Irving,TX,75037
4,104,Martha,Cooper,mcooper4@go.com,(727)235-5696,4537 Hoard Lane,Tampa,FL,33625

In [23]:
sample_customers_data.columns

Index(['CustomerID', 'FirstName', 'LastName', 'Email', 'Phone', 'Address',
       'City', 'State', 'Zipcode'],
      dtype='object')

In [24]:
#checking duplicated rows based on Email, Phone, FirstName, LastName columns
columns_to_check = ['Email', 'Phone', 'FirstName', 'LastName']
duplicates = sample_customers_data[sample_customers_data.duplicated(columns_to_check)]
duplicates.shape

(29, 9)

In [25]:
#now we are storing not duplicated rows in the original sample_customers_data.
sample_customers_data = sample_customers_data.drop_duplicates(subset=columns_to_check)
sample_customers_data.shape

(1000, 9)

In [26]:
#This part is used to check if there are nulls and missing values in the customers data.
sample_customers_data.isnull().sum()

CustomerID    0
FirstName     0
LastName      0
Email         0
Phone         0
Address       0
City          0
State         0
Zipcode       0
dtype: int64

In [27]:
#In this part we are loading employees-table data.
sample_employees_data = pd.read_excel(source_path_employees, sheet_name='Employees-Table')
#sample_employees_data.head()

In [28]:
#In this part we are transforming employees data as per business need.
#sample_employees_data.columns
drop_columns = ['Job Rating', 'New Salary', 'Tax Rate', '2.91%']
sample_employees_data = sample_employees_data.drop(columns=drop_columns)
sample_employees_data.head()

,Employee Name,Building,Department,Status,Hire Date,Month,Years,Benefits,Salary
0,"Page, Lisa",West,ADC,Full Time,1999-01-11,Jan,25,DMR,24550
1,"Taylor, Hector",West,ADC,Half-Time,2011-02-21,Feb,12,DM,26795
2,"Dawson, Jonathan",West,ADC,Contract,2007-03-06,Mar,16,NaN,42540
3,"Duran, Brian",Taft,ADC,Hourly,2012-08-30,Aug,11,NaN,35680
4,"Weber, Larry",Watson,ADC,Full Time,2007-12-31,Dec,16,M,72830